### ISSUE TITLE
artic pipeline not installing properly: ModuleNotFoundError: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by aduton2000** [artic-network/fieldbioinformatics#108]
Hello,
I have installed the artic pipeline several times on different computers following the installation instructions provided at this fieldbioinformatics github page. However, for the past two days, the same instructions don't seem to work when I try installing the pipeline. The issue is that, during the installation, everything gets downloaded and the process goes on with no obvious error as far as I can tell. When everything is done and I activate the artic environment and try to check the artic version (using artic -v), I get couple of errors as follows:
`artic -v
Traceback (most recent call last):
  File "/home/genomicslab/miniconda3/envs/artic/bin/artic", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/genomicslab/miniconda3/envs/artic/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 9, in <module>
    from typing import Protocol
ImportError: cannot import name 'Protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/genomicslab/miniconda3/envs/artic/bin/artic", line 13, in <module>
    from importlib_metadata import distribution
  File "/home/genomicslab/miniconda3/envs/artic/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 17, in <module>
    from . import _adapters, _meta
  File "/home/genomicslab/miniconda3/envs/artic/lib/python3.6/site-packages/importlib_metadata/_meta.py", line 1, in <module>
    from ._compat import Protocol
  File "/home/genomicslab/miniconda3/envs/artic/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 16, in <module>
    from typing_extensions import Protocol  # type: ignore
  File "/home/genomicslab/miniconda3/envs/artic/lib/python3.6/site-packages/typing_extensions.py", line 159, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'
`
My computer spec: Intel® Core™ i3-4160 CPU @ 3.60GHz × 4 
OS name: Ubuntu 21.10

I would be truly grateful if anyone could help me fix this issue.
Thanks a lot.

**Comment by BioWilko** [comment]
Despite being able to reproduce this when the issue was posted I now cannot. If anyone else confirms they are experiencing the issue please reply but otherwise I'm going to consider it solved.
